#!/usr/bin/env bash
# transfer file ‘file’ to a server
# scp /path/to/file username@a:/path/to/destination

# if number of arguments is >= 3
if [ "$#" -lt 3 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ];
then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
