#!/usr/bin/env bash
# Transfer file ‘file’ to a server
# scp /path/to/file username@a:/path/to/destination

#If number of arguments is >= 3
if [ "$#" -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
if [ "$4" == "" ]
then
	scp -o "StrictHostKeyChecking no" "$1" "$3"'@'"$2":~/
else
	scp -i "$4" -o "StrictHostKeyChecking no" "$1" "$3"'@'"$2":~/
fi
