#!/usr/bin/env bash
# Create a script to install and config HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 server


sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y update
sudo apt-get -y install haproxy
sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sed -i -e '$a\listen balancer\n\tbind :80\n\tbalance roundrobin\n\tserver 91745-web-01 54.164.103.65 check\n\tserver 91745-web-02 107.22.143.21 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
