#!/usr/bin/env bash
# Run a daemon process
# The general minimum set of instructions is: start, restart and stop.

PIDFILE=/var/run/my_process.pid

# START
if [ "$1" = "start" ]; then
	./manage_my_process &
	echo "$!" > "$PIDFILE"
	echo manage_my_process started
# STOP
elif [ "$1" = "stop" ]; then
	pkill -SIGKILL -f ./manage_my_process
	rm "$PIDFILE"
	echo manage_my_process stopped
# RESTART
elif [ "$1" = "restart" ]; then
	pkill -SIGKILL -f ./manage_my_process
	rm "$PIDFILE"
	./manage_my_process &
	echo "$!" > "$PIDFILE"
	echo manage_my_process restarted
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
