#!/usr/bin/env bash
# To infinity and beyond indefinitely 2 sleep and invincible sigterm.
while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
