#!/usr/bin/env bash
# Displays the contents of the f `/etc/passwd`.
# Shows the username, user id, and user home directory path.

inFile="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$inFile"
