#!/usr/bin/env bash
# Display content of the file /etc/passwd, using the while loop + IFS.
exec 3< /etc/passwd
while IFS=: read -r -a param -u 3; do
	echo The user "${param[0]}" is part of the "${param[3]}" gang, lives\
 in "${param[5]}" and rides "${param[6]}". "${param[2]}"\'s place is\
 protected by the passcode "${param[1]}", more info about the user here:\
 "${param[4]}"
done
