#!/usr/bin/env bash
# Displays the visitor IP along with the HTTP status code sorted
# The exact format; OCCURENCE_NUMBER IP HTTP_CODE In list format
# Ordered from the greatest to the lowest number of occurrences

awk '{ print $1,$9 }' apache-access.log | sort | uniq -c | sort -rn
