#!/usr/bin/env bash
# Displays hours from 0 to 12
# Displays minutes from 1 to 59

counts=0

while [ $counts -le 12 ]
do
  echo "Hour: $counts"
  minute=1
  while [ $minute -le 59 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( counts++ ))
done
